# Tavok Setup Script (Windows)
# Generates .env with secure random secrets.
#
# Usage:
#   .\scripts\setup.ps1                          # interactive (prompts for domain)
#   .\scripts\setup.ps1 -Domain example.com      # non-interactive
#   .\scripts\setup.ps1 -Domain localhost         # non-interactive, localhost

param(
    [string]$Domain = ""
)

$ErrorActionPreference = "Stop"

Write-Host ""
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host "        Tavok Setup Script" -ForegroundColor Cyan
Write-Host "=======================================" -ForegroundColor Cyan
Write-Host ""

# Check for existing .env
if (Test-Path .env) {
    if ($Domain -ne "") {
        Write-Host ".env already exists. Overwriting (-Domain flag passed)."
    } else {
        $confirm = Read-Host ".env already exists. Overwrite? (y/N)"
        if ($confirm -ne "y" -and $confirm -ne "Y") {
            Write-Host "Aborted."
            exit 0
        }
    }
}

# Generate secrets using .NET crypto
function New-Secret($bytes = 32) {
    $buf = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($buf)
    return [Convert]::ToBase64String($buf)
}

function New-HexSecret($bytes = 32) {
    $buf = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($buf)
    return ($buf | ForEach-Object { $_.ToString("x2") }) -join ""
}

function New-AlphaSecret($length = 20) {
    $buf = New-Object byte[] $length
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($buf)
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
    return -join ($buf | ForEach-Object { $chars[$_ % $chars.Length] })
}

$NEXTAUTH_SECRET = New-Secret
$JWT_SECRET = New-Secret
$INTERNAL_API_SECRET = New-Secret
$SECRET_KEY_BASE = New-Secret 64
$ENCRYPTION_KEY = New-HexSecret
$POSTGRES_PASSWORD = New-AlphaSecret
$REDIS_PASSWORD = New-Secret

# Determine domain
if ($Domain -ne "") {
    $DOMAIN = $Domain
} else {
    Write-Host ""
    $DOMAIN = Read-Host "Your domain (e.g., chat.example.com) or press Enter for localhost"
    if ([string]::IsNullOrWhiteSpace($DOMAIN)) { $DOMAIN = "localhost" }
}

if ($DOMAIN -eq "localhost") {
    $NEXTAUTH_URL = "http://localhost:5555"
    $GATEWAY_WS_URL = "ws://localhost:4001/socket"
} else {
    $NEXTAUTH_URL = "https://$DOMAIN"
    $GATEWAY_WS_URL = "wss://$DOMAIN/socket"
}

$envContent = @"
# Tavok Configuration
# Generated by setup.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm:ss UTC")
# Keep this file secret. Never commit it to git.

# ============================================================
# DOMAIN & URLs
# ============================================================

DOMAIN=$DOMAIN
NEXTAUTH_URL=$NEXTAUTH_URL
NEXT_PUBLIC_GATEWAY_URL=$GATEWAY_WS_URL

# ============================================================
# DATABASE
# ============================================================

POSTGRES_USER=tavok
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_DB=tavok
DATABASE_URL=postgresql://tavok:${POSTGRES_PASSWORD}@db:5432/tavok

# ============================================================
# REDIS
# ============================================================

REDIS_PASSWORD=$REDIS_PASSWORD

# ============================================================
# SECRETS (auto-generated, do not share)
# ============================================================

NEXTAUTH_SECRET=$NEXTAUTH_SECRET
JWT_SECRET=$JWT_SECRET
INTERNAL_API_SECRET=$INTERNAL_API_SECRET
SECRET_KEY_BASE=$SECRET_KEY_BASE
ENCRYPTION_KEY=$ENCRYPTION_KEY

# ============================================================
# SERVICE PORTS
# ============================================================

GATEWAY_PORT=4001
STREAMING_PORT=4002

# ============================================================
# ENVIRONMENT
# ============================================================

NODE_ENV=production
MIX_ENV=prod
"@

$envContent | Out-File -FilePath .env -Encoding utf8 -NoNewline

Write-Host ""
Write-Host ".env file created with secure secrets." -ForegroundColor Green
Write-Host ""
if ($DOMAIN -ne "localhost") {
    Write-Host "Next steps:"
    Write-Host "  1. Point DNS for $DOMAIN to this server's IP"
    Write-Host "  2. Run: docker compose --profile production up -d"
    Write-Host "  3. Open https://$DOMAIN"
} else {
    Write-Host "Next steps:"
    Write-Host "  1. Run: docker compose up -d"
    Write-Host "  2. Open http://localhost:5555"
}
Write-Host ""
